# This workflow download epapers from the server & save it on our repo

name: Copy-Saved-ePapers

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 12 * * *' # every morning at 5:30PM IST 12:00PM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Download-and-save-epapers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Copy previously saved epapers
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          src_branch: publish
          src_path: /epapers/.
          dst_path: /public/epapers/
          dst_branch: main
          dst_owner: thelazyshell
          dst_repo_name: ie-newspaper