# This workflow download epapers from the server & save it on our repo

name: Copy-Saved-ePapers

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 12 * * *' # every morning at 5:30PM IST 12:00PM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Download-and-save-epapers:
    runs-on: ubuntu-latest
    steps:
          
      - name: Delete old epapers
        run: |
          pwd
