# This workflow download epapers from the server & save it on our repo

name: Download-Latest-ePapers

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 23 * * *' # every morning at 4:30AM IST 11:00PM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Download-and-publish-latest-epapers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: setup-node
        uses: actions/setup-node@master

      - name: Build app and wget todays epaper in epaper folder
        run: |
          npm install
          npm run build
          echo "built completed"
          cd docs
          cd epapers
          echo "i am inside epapers folder"          
          sevenDayOldDays=`date  --date="7 days ago" +"%d-%m-%Y"`
          rm -r sevenDayOldDays
          abhiKaTime=`date +"%H"`
          if [ $abhiKaTime  -eq  '23' ]
          then
            fileKiDate=`date  --date="next day" +"%d-%m-%Y"`
          else
            fileKiDate=`date +%d-%m-%Y`
          fi
          echo "downloading ${fileKiDate} files at ${abhiKaTime}"
          mkdir $fileKiDate
          cd $fileKiDate
          echo "Starting download"
          wget -q -O ahmedabad.pdf "${{ secrets.PAPER_URL_A }}${fileKiDate}.pdf"
          wget -q -O chandigarh.pdf "${{ secrets.PAPER_URL_C }}${fileKiDate}.pdf"
          wget -q -O delhi.pdf "${{ secrets.PAPER_URL_D }}${fileKiDate}.pdf"
          wget -q -O jaipur.pdf "${{ secrets.PAPER_URL_J }}${fileKiDate}.pdf"
          wget -q -O kolkata.pdf "${{ secrets.PAPER_URL_K }}${fileKiDate}.pdf"
          wget -q -O lucknow.pdf "${{ secrets.PAPER_URL_L }}${fileKiDate}.pdf"
          wget -q -O mumbai.pdf "${{ secrets.PAPER_URL_M }}${fileKiDate}.pdf"
          wget -q -O pune.pdf "${{ secrets.PAPER_URL_P }}${fileKiDate}.pdf"
          echo "Download finished"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: publish # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
